#!/bin/bash

SUPER_SIZE=$((7 * 1024 * 1024 * 1024))
ALIGN=$((4 * 1024 * 1024))

lpmake \
    -d $SUPER_SIZE \
    --metadata-size=65536 \
    --metadata-slots=3 \
    --alignment=$ALIGN \
    --alignment-offset=$ALIGN \
    --super-name=super \
    --virtual-ab \
    -g qti_dynamic_partitions_a:$(($SUPER_SIZE - $ALIGN)) \
    -g qti_dynamic_partitions_b:$(($SUPER_SIZE - $ALIGN)) \
    -p odm_a:readonly:0:qti_dynamic_partitions_a \
    -p odm_b:readonly:0:qti_dynamic_partitions_b \
    -p product_a:readonly:0:qti_dynamic_partitions_a \
    -p product_b:readonly:0:qti_dynamic_partitions_b \
    -p system_ext_a:readonly:0:qti_dynamic_partitions_a \
    -p system_ext_b:readonly:0:qti_dynamic_partitions_b \
    -p system_a:readonly:0:qti_dynamic_partitions_a \
    -p system_b:readonly:0:qti_dynamic_partitions_b \
    -p vendor_dlkm_a:readonly:0:qti_dynamic_partitions_a \
    -p vendor_dlkm_b:readonly:0:qti_dynamic_partitions_b \
    -p vendor_a:readonly:0:qti_dynamic_partitions_a \
    -p vendor_b:readonly:0:qti_dynamic_partitions_b \
    -o super_empty.img
